// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFp1iF0NsxiReXUBc6hR6FrV6caL5locM',
    appId: '1:1085433900261:web:447fea517325ef4c53b80c',
    messagingSenderId: '1085433900261',
    projectId: 'fitsync-2295b',
    authDomain: 'fitsync-2295b.firebaseapp.com',
    storageBucket: 'fitsync-2295b.firebasestorage.app',
    measurementId: 'G-C5JTR31H96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBeHWrI9AXiGC4s8Hm0JPwJv4LnETJdtw',
    appId: '1:1085433900261:android:042ed687610419ae53b80c',
    messagingSenderId: '1085433900261',
    projectId: 'fitsync-2295b',
    storageBucket: 'fitsync-2295b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAyAWHDBQ1cRXC8W5uEFz9UYmG24ZQPxQ',
    appId: '1:1085433900261:ios:2b5de4874f8d429c53b80c',
    messagingSenderId: '1085433900261',
    projectId: 'fitsync-2295b',
    storageBucket: 'fitsync-2295b.firebasestorage.app',
    iosBundleId: 'com.example.fitsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAyAWHDBQ1cRXC8W5uEFz9UYmG24ZQPxQ',
    appId: '1:1085433900261:ios:2b5de4874f8d429c53b80c',
    messagingSenderId: '1085433900261',
    projectId: 'fitsync-2295b',
    storageBucket: 'fitsync-2295b.firebasestorage.app',
    iosBundleId: 'com.example.fitsyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFp1iF0NsxiReXUBc6hR6FrV6caL5locM',
    appId: '1:1085433900261:web:61180ce52041e0b753b80c',
    messagingSenderId: '1085433900261',
    projectId: 'fitsync-2295b',
    authDomain: 'fitsync-2295b.firebaseapp.com',
    storageBucket: 'fitsync-2295b.firebasestorage.app',
    measurementId: 'G-TQJFHRSPWD',
  );
}
